import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Logo from '../assets/cc-logo.png'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Crowd Creators</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img className={styles.logo} src={Logo.src} /> 
        <h1 className={styles.title}>
          Welcome to Crowd Creators
        </h1>

        <p className={styles.description}>
          We help creators collaborate to create amazing things!
        </p>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
